### ISSUE TITLE
freezing upon loading in Ableton Live 10

### ISSUE THREAD

**Issue by funkyrod99** [ales-tsurko/kotoist#2] opened 2021-10-28 04:43 UTC
Hi,

Trying this out in Ableton Live 10 and it freezes when loading.  Attached a screenshot of what I see in Ableton - it just shows "Loading..." and i am never able to input code
![Screen Shot 2021-10-27 at 9 41 25 PM](https://user-images.githubusercontent.com/75760077/139188373-84a2ef21-cbb8-40fe-82d5-65f0ee990659.png)

**Comment by ales-tsurko** [comment] 2021-10-28 06:09
Hi! Thanks for the report. I'll take a look when I have free time.

**Comment by ales-tsurko** [comment] 2021-10-29 15:25
Sorry, I can't reproduce it. But I only have Ableton 11. Try to reopen the editor. Make sure you use the latest Kotoist version: https://github.com/ales-tsurko/kotoist/releases

**Comment by funkyrod99** [comment] 2021-10-29 18:21
Hi Ales,

I followed the link and downloaded the latest version, but still get the same result — just shows the “loading….”   I can click on the snippets tab and see the grid and the snippets, but can’t see where I would enter the code.  When I switch back to the editor it only shows “Loading…” and doesn’t allow me to type anything.
Also tried it in Reason and get the same result.  I’m on a mac running Mojave.

Should I be clicking on something else when it opens to get past the Loading…?


Rodney

**Comment by ales-tsurko** [comment] 2021-10-29 19:00
> I’m on a mac running Mojave.

This may be the reason, as it's compiled on Catalina. It uses webview for GUI under the hood. Monaco editor may not be compatible with older versions of macOS.

Anyway, when I tried it in Ableton, I discovered that it's not sending MIDI messages. While it's ok on the plugin level and all events are passed to the host, for some reason Ableton don't see those events.

So far I've tested the plugin in: Reaper, FL Studio and Usine. In these hosts it should work as expected.

As an independent developer, having very little free time, I have no possibility to cover all hosts, unfortunately, and I hope for contributions.

**Comment by funkyrod99** [comment] 2021-10-29 19:05
yep that’s probably the issue.  I’ll wait until I update my OS and try again then.

Thank you so much for looking into it!

best,

rodney

**Comment by ales-tsurko** [comment] 2024-11-24 21:29
> Anyway, when I tried it in Ableton, I discovered that it's not sending MIDI messages. While it's ok on the plugin level and all events are passed to the host, for some reason Ableton don't see those events.

Should work in Ableton now.

For the rest I'm closing it as only the latest version of macOS is supported. For earlier versions you have to compile it from source.

**Closed as completed by ales-tsurko** 2024-11-24 21:29 UTC
